name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ttsfreeinsta.azurecr.io
        username: ttsfreeinsta$ttsfreeinsta
        password: 0nKJhYc22l1HxexNtcug6pNdPNLPywKqSj4E72lyK483SwNxHmz3qQhc0JW7

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ttsfreeinsta.azurecr.io/tts-web:latest