# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ttsfreeinsta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_09738d2509a14fe59716eceee3e01090 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_107dbed2dcfb4f5988b97c9500f7b0a2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_09738d2509a14fe59716eceee3e01090 }}/teste:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ttsfreeinsta'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ea849c53d9e42ae8ff19805e0ec3de6 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_09738d2509a14fe59716eceee3e01090 }}/teste:${{ github.sha }}'